services:
  jenkins:
    build:
      context: ./jenkins  # Jenkins 코드가 있는 폴더
      dockerfile: Dockerfile  # Jenkins용 Dockerfile
    # image: jenkins/jenkins:lts  # 최신 LTS 버전 사용
    environment:
      - TZ=Asia/Seoul
    container_name: my-jenkins
    user: root  # 권한 문제 방지 (필수)
    ports:
      - "8081:8080"  # 웹 UI 접근 (기본 포트 8080)
      - "50000:50000"  # 에이전트와 통신용 포트
    volumes:
      - /home/ubuntu/jenkins_data:/var/jenkins_home  # Jenkins 데이터 유지
      - /var/run/docker.sock:/var/run/docker.sock  # Docker 컨테이너 제어를 위해 필요
    restart: always

  db:
    image: mysql:8
    container_name: my-mysql
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - /home/ubuntu/mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: always
    

networks:
  app-network:
    name: app-network  # ✅ 공통 네트워크 설정
    driver: bridge

volumes:
  mysql-data: