server:
  port: 8080

spring:
  elasticsearch:
    uris: http://my-elasticSearch:9200  # Docker Compose에서 설정한 컨테이너 이름 사용
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://my-mysql:3306/recipidia?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: ${MYSQL_ROOT_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    #      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

logging.level:
  org.hibernate.SQL: DEBUG

springdoc:
  swagger-ui:
    path: /index.html

fastapi:
  base:
    url: http://localhost:8000
