server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev
  elasticsearch:
    uris: http://localhost:9200  # Docker Compose에서 설정한 컨테이너 이름 사용
    username: elastic
    password: 123456
  datasource:
    url: jdbc:h2:tcp://localhost/~/recipidia
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    open-in-view: false

logging.level:
  org.hibernate.SQL: DEBUG
  org.springframework:
    security: DEBUG
    web.socket: DEBUG
    messaging: DEBUG
  org.elasticsearch.client: DEBUG
  org.springframework.data.elasticsearch: DEBUG

springdoc:
  swagger-ui:
    path: /index.html

fastapi:
  base:
    url: http://localhost:8000
